renegade-fi/typescript-sdk

- packages/core/src/createConfig.ts
- packages/react/src/hooks/useConfig.ts
This PR adds generics to the createConfig function so that the utils object can be properly typed based on which environment it is in (web vs. node).
> core, react: properly type utils object in config

- packages/core/src/createConfig.ts
This PR allows for an insecure transport to be used by setting the `useInsecreTransport` option in the config.
> core: Allow for specifying useInsecureTransport on config object

- packages/core/src/constants.ts
- packages/core/src/types/task.ts
- packages/core/src/types/wallet.ts
- packages/core/src/utils/http.ts
- packages/react/src/hooks/useOrderHistory.ts
- packages/react/src/hooks/useTaskHistory.ts
This PR changes the transform function when `GET`ting data from the API to parse all numerical values as bigint. This makes the data more consistent, as numerical values within the safe number boundaries of javascript were being processed as `number`, even if it's type was `bigint`.
> core, react: parse all numerical values as bigint for consistency

- packages/core/CHANGELOG.md
- packages/core/package.json
- packages/node/CHANGELOG.md
- packages/node/package.json
- packages/react/CHANGELOG.md
- packages/react/package.json
- packages/test/CHANGELOG.md
- packages/test/package.json
- wasm/Cargo.toml
- wasm/src/common/keychain.rs
This PR updates the `sign_commitment` method on the `Wallet` struct to serialize the commitment using the `BytesSerializable` trait defined in the contracts repo. The rationale for why this is necessary is laid out in https://github.com/renegade-fi/renegade/pull/589
> wasm: common: keychain: use contracts ByteSerializable in sig gen

- packages/core/src/createConfig.ts
- packages/core/src/hydrate.ts
- packages/core/src/utils.d.ts
This PR removes the option to reinitialize config.store, as it resulted in subscribers losing access to subscription, since a new store was being instantiated. Replaced by client side handling.
> core: remove no persist option

- biome.json
- packages/core/src/actions/createOrder.ts
This PR adds a check to the `createOrder` action to panic if an order would result in too many balances. This happens if the user has a full balance array and is attempting to buy a mint that does not already exist in the balances array.
> core: error if order would result in too many balances

- packages/core/src/utils/format.ts
This PR allows for the number of decimals to truncate to to be passed as a parameter to the `formatAmount` function.
> core: allow for dynamic decimal truncation

- packages/core/src/actions/connect.ts
- packages/core/src/actions/createWallet.ts
- packages/core/src/actions/lookupWallet.ts
- packages/core/src/actions/waitForWalletIndexing.ts
This PR adds `waitForWalletIndexing` which is used during the onboarding step to ensure that the internal state of the SDK is correctly updated when wallets are indexed, or created, in the connected relayer. Previously, incorrect states were being reached because we were checking the completion of the `lookup-wallet` or `create-wallet` task.
> core: add function to wait for wallet indexing

- packages/react/src/hooks/useNetworkOrders.ts
This PR prevents orderbook refetching (both on an interval and on window refocus) to prevent the orderbook flickering in the frontend. This is due to the orderboo not being a part of consensus in multinode environments.
> react: prevent orderbook refetching

- packages/core/src/actions/createOrder.ts
- packages/core/src/actions/deposit.ts
- packages/core/src/actions/getBackOfQueueWallet.ts
- packages/core/src/constants.ts
- packages/core/src/index.ts
- packages/core/src/query/getBackOfQueueWallet.ts
- packages/react/src/hooks/useBackOfQueueBalances.ts
- packages/react/src/hooks/useBackOfQueueOrders.ts
- packages/react/src/hooks/useBackOfQueueWallet.ts
- packages/react/src/hooks/useNetworkOrders.ts
This PR adds queries for back of queue API endpoints. Also removes safety checks in deposit and create order actions since they are now implemented in the frontend.
> core, react: add back of queue queries

- packages/core/src/utils/viem.ts
This PR removes the placeholder block explorer URL.
Tested in frontend that the network is still automatically added.
> core: remove placeholder block explorer url

- packages/core/package.json
- packages/core/src/actions/refreshWallet.ts
- packages/core/src/constants.ts
- packages/core/src/exports/actions.ts
- packages/react/package.json
- pnpm-lock.yaml
This PR adds the action for `refresh-wallet` as defined in https://github.com/renegade-fi/renegade/pull/657
> core: add refresh wallet task

- packages/core/src/actions/lookupWallet.ts
This PR increases the timeout to wait for lookup wallet indexing to 5 min.
> core: increase lookup wallet timeout

- packages/core/src/actions/lookupWallet.ts
This PR fixes logs in the `lookup-wallet` action to properly log the task id and wallet id.
> core: fix lookup wallet log

- packages/core/package.json
- packages/core/src/actions/connect.ts
- packages/core/src/actions/createWallet.ts
- packages/core/src/actions/disconnect.ts
- packages/core/src/actions/getBackOfQueueWallet.ts
- packages/core/src/actions/getSkRoot.ts
- packages/core/src/actions/getWalletFromRelayer.ts
- packages/core/src/actions/getWalletId.ts
- packages/core/src/actions/lookupWallet.ts
- packages/core/src/actions/reconnect.ts
- packages/core/src/actions/waitForWalletIndexing.ts
- packages/core/src/createConfig.ts
- packages/core/src/exports/actions.ts
- packages/core/src/exports/index.ts
- packages/core/src/hydrate.ts
- packages/core/src/query/getBackOfQueueWallet.ts
- packages/core/src/query/getWallet.ts
- packages/react/package.json
- packages/react/src/hooks/useBackOfQueueWallet.ts
- packages/react/src/hooks/useWallet.ts
This PR adds checks in the `setState` function to prevent invalid state transitions. Also removes the `seed` parameter from functions, opting to instead use the seed stored in state on the `config` object.
> core, react: remove unecessary `seed` parameter, safeguard state transitions

- biome.json
- packages/core/src/actions/getBackOfQueueWallet.ts
- packages/core/src/actions/getOrder.ts
- packages/core/src/actions/getOrderHistory.ts
- packages/core/src/actions/getOrders.ts
- packages/core/src/actions/getWalletFromRelayer.ts
- packages/core/src/exports/index.ts
- packages/core/src/types/order.ts
- packages/core/src/types/task.ts
- packages/core/src/types/wallet.ts
- packages/core/src/utils/http.ts
- packages/react/src/hooks/useOrderBookWebSocket.ts
- packages/react/src/hooks/useOrderHistoryWebSocket.ts
- packages/react/src/hooks/useTaskHistoryWebSocket.ts
- packages/react/src/hooks/useWalletWebSocket.ts
This PR downstreams API response type changes from the relayer that adds more data to the `OrderMetadata` type and `PayFeeTask` type. Also refactors order-related types into their own file for readability.
> core: downstream API changes for orders / tasks

- packages/node/src/index.ts
This PR exports actions and constants from `core` to the `node` package.
> node: export core actions and constants

- packages/node/CHANGELOG.md
- packages/node/package.json
- packages/node/src/index.ts
This PR fixes a typo in the import in the `node` package.
> node: fix index import

- packages/core/src/actions/watchInitialized.ts
- packages/core/src/createConfig.ts
- packages/core/src/exports/index.ts
- packages/core/src/query/getBackOfQueueWallet.ts
- packages/core/src/query/getOrderHistory.ts
- packages/core/src/query/getTaskHistory.ts
- packages/core/src/query/getWallet.ts
- packages/react/src/exports/index.ts
- packages/react/src/hooks/useInitialized.ts
- packages/react/src/hydrate.ts
This PR scopes each query hook to the wallet it is querying data for, fixes issues with multiple configs in one app. Also adds a useInitialized hook to ensure that the WASM module has been initialized before calling functions.
> core, react: changes for quoter dashboard

- packages/core/CHANGELOG.md
- packages/core/package.json
- packages/core/src/utils/viem.ts
- packages/node/CHANGELOG.md
- packages/node/package.json
- packages/react/CHANGELOG.md
- packages/react/package.json
- packages/react/src/hydrate.ts
- packages/test/CHANGELOG.md
- packages/test/package.json
This PR adds the Arbitrum Sepolia chain to the SDK, to be used by setting the `CHAIN_ID` env variable.
> core: add Arbitrum Sepolia chain

- packages/react/src/exports/index.ts
This PR exposes the `PartialOrderFill` type for consumption in the frontend
> packages: react: exports: export PartialOrderFill

- packages/core/src/actions/reconnect.ts
- packages/core/src/createConfig.ts
- packages/core/src/exports/index.ts
- packages/core/src/hydrate.ts
- packages/core/src/utils/cookie.ts
- packages/react/src/exports/index.ts
- packages/react/src/hydrate.ts
This PR exports the cookieStorage module for usage as a storage option when persisting state. Also makes changes to ensure hydrating from a cookie works, especially when using SSR.
> core, react: export cookiestorage

- packages/react/CHANGELOG.md
- packages/react/package.json
- packages/react/src/hooks/useBalances.ts
- packages/react/src/hooks/useFees.ts
- packages/react/src/hooks/useOrders.ts
This PR refactors `useBalances` `useOrders` `useFees` to return Map types instead of Array for easier indexing.
> trade: refactor useBalances useOrders useFees to return Map

- packages/core/src/actions/createMatchingPool.ts
- packages/core/src/actions/destroyMatchingPool.ts
- packages/core/src/constants.ts
- packages/core/src/exports/actions.ts
- packages/core/src/utils/http.ts
This PR adds 2 actions for the creation & destruction of matching pools via a relayer's admin API. This will be tested via consumption in the internal dashboard app
> core: actions: matching pool create/destroy

- packages/core/src/actions/getOrderMetadata.ts
- packages/core/src/constants.ts
- packages/core/src/exports/actions.ts
- packages/core/src/exports/query.ts
- packages/core/src/query/getOrderMetadata.ts
- packages/react/src/exports/index.ts
- packages/react/src/hooks/useOrderMetadata.ts
This PR introduces a core action + React hook for getting a given order's metadata via the admin API of a relayer to which one has admin access. This will be tested via consumption in the internal dashboard app.
> packages: core, react: get order metadata action / hook

- packages/core/src/actions/getOrderMetadata.ts
- packages/core/src/utils/http.ts
This PR adjusts the `getRelayerRaw` helper to properly parse prices from the `/admin/orders/:id/metadata` endpoint. This is done a bit fuzzily at the moment by checking if the URL simply includes the `/metadata` path fragment, but this is okay b/c 1) this is currently the only endpoint with that fragment, and 2) we are planning on changing this helper soon anyway to do custom parsing
> core: utils: http: parse prices from admin order metadata field correctly

- packages/core/src/actions/connect.ts
- packages/core/src/actions/lookupWallet.ts
This PR prevents create wallet tasks being sent to the relayer in the case of an error while getting events using the public RPC. Now, a create wallet request is sent to the relayer if and only if the get events request returns successfully and contains 0 logs.
> core: prevent create wallet when rpc getLogs req fails

- packages/core/CHANGELOG.md
- packages/core/package.json
- packages/core/src/actions/connect.ts
- packages/core/src/exports/index.ts
- packages/node/CHANGELOG.md
- packages/node/package.json
- packages/react/CHANGELOG.md
- packages/react/package.json
- packages/test/CHANGELOG.md
- packages/test/package.json
This PR allows for the library consumer to pass a flag to `connect` that will force a create wallet task to be executed. This is used to offload fetching of logs to the consumer.
> core: allow client to get logs and force create wallet in connect

- packages/core/src/actions/getOpenOrders.ts
- packages/core/src/exports/actions.ts
- packages/core/src/query/getOpenOrders.ts
- packages/core/src/types/order.ts
This PR updates the `getOpenOrders` action to support an optional `?matching_pool` query param & expect a different response shape in accordance w/ https://github.com/renegade-fi/renegade/pull/711. This will be tested in downstream consumption of the SDK.
> core: actions: getOpenOrders: add pool query param

- packages/core/src/types/order.ts
This PR updates the `OpenOrder` API type to include the `price` field (used to calculate the fillable amount) in accordance w/ https://github.com/renegade-fi/renegade/pull/711.
The fetch helper in `http.ts` already conditionally parses fields titled `price` as numbers for the `/open-orders` endpoint, so this field should be parsed appropriately.
> core: types: order: add price field to openorder

- packages/core/src/actions/getOpenOrders.ts
This PR exposes the `include_fillable` query parameter on the `/admin/open-orders` endpoint, which instructs the relayer to compute the total fillable amount for each open order. The logic for this is already present relayer-side, we just never included it in the action.
> core: actions: getOpenOrders: add include_fillable param

- packages/core/src/actions/waitForTaskCompletion.ts
- packages/core/src/actions/waitForTaskCompletionWs.ts
- packages/core/src/exports/actions.ts
- packages/core/src/exports/index.ts
- packages/core/src/types/ws.ts
- packages/core/src/utils/websocketWaiter.ts
This PR introduces a generic primitive for awaiting results on short-lived websocket connections, & uses it to create a websocket-based task completion waiter. This can be used to avoid polling-based waiters on the relayer, which may result in the client being rate-limited.
I tested this locally by using it in the bot server's `refresh-quoters` endpoint & asserting that the task completion waiter resolved when expected
> core: websocket waiter primitive

- packages/core/src/types/token.ts
This PR makes the `Token.findByAddress` method case-insensitive, in case the token mapping uses checksum addresses (as is currently the case w/ the mainnet token mapping).
> core: types: token: make findByAddress case-insensitive

- packages/core/src/types/token.ts
- packages/node/package.json
- packages/node/src/actions/executeDeposit.ts
- packages/node/src/actions/executeWithdrawal.ts
- packages/node/src/exports/actions.ts
- packages/node/src/exports/index.ts
- packages/node/src/generated.ts
- packages/node/src/utils/permit2.ts
- packages/node/tsconfig.json
- packages/node/wagmi.config.ts
- pnpm-lock.yaml
This PR introduces the notion of "composite actions" to the `node` package, exposing higher-level sequences of actions that embody notions like "withdraw" and "deposit". This papers over e.g. paying fees ahead of withdrawal, or signing a permit ahead of a deposit. The Permit2 utilities were mostly copied over from the UI.
This was tested downstream during development of our internal dashboard app.
> node: actions: composite withdraw & deposit

- packages/core/src/actions/getWalletFromRelayer.ts
This PR removes the `setState` function call in `getWalletFromRelayer` as it was causing issues in certain cases when a disconnect was called, but the relayer responded with the wallet object, resulting in an inconsistent `{ seed: undefined, status: "in relayer" } `state. It's a better separation of concerns for only functions directly related to connecting / disconnecting to modify these state variables anyways.
> core: remove set state in getWallet fn

- packages/core/src/utils/http.ts
This PR adds a clause for the price reporter's `/price` route in the `getRelayerRaw` method that ensures the result is not parsed using `parseBigJSON`.
This is currently what happens, but for float prices it would error and we would just `return data` directly, i.e. the `number` type.
However, whole number prices would get successfully parsed into `BigInt`s, violating the return type expected in the `getPriceFromPriceReporter` function signature.
> core: utils: http: use default json parsing for price reporter fetch

- packages/node/CHANGELOG.md
- packages/node/package.json
- packages/node/src/exports/actions.ts
- packages/node/src/exports/index.ts
This PR ensures actions in the `node` package are also exported from the entry module in addition to the `/actions` namespace.
> node: export actions from entry module

- packages/core/CHANGELOG.md
- packages/core/package.json
- packages/core/src/actions/getOrderHistory.ts
- packages/core/src/constants.ts
- packages/core/src/exports/index.ts
- packages/node/CHANGELOG.md
- packages/node/package.json
- packages/react/CHANGELOG.md
- packages/react/package.json
- packages/test/CHANGELOG.md
- packages/test/package.json
This PR exposes a `limit` parameter for the `getOrderHistory` action that allows for consumers to limit the response sent from the API server.
> core: expose limit parameter for getOrderHistory

- packages/core/src/actions/getOrderMatchingPool.ts
- packages/core/src/constants.ts
- packages/core/src/exports/actions.ts
- packages/core/src/exports/index.ts
This PR adds an SDK action for the new "get order matching pool" relayer endpoint
> core: actions: add getOrderMatchingPool action

- package.json
- packages/core/src/actions/waitForTaskCompletionWs.ts
- packages/core/src/exports/index.ts
- packages/core/src/utils/websocket.ts
- packages/core/src/utils/websocketWaiter.ts
- packages/node/src/exports/index.ts
- packages/react/src/exports/index.ts
- pnpm-lock.yaml
This PR swaps out the deprecated `WebsocketManager` class for a lightweight `RelayerWebsocket` class which handles subscribing to a single relayer topic w/ the associated auth. Reconnection management is deferred to the consuming client.
This utility supports admin auth, which is now available as an authentication method for some websocket topics ([ref](https://github.com/renegade-fi/renegade/pull/796))
We then leverage this new class within the `websocketWaiter` utility.
Testing will occur downstream of integration into the internal quoter server
> core: utils: websocket: create relayer ws wrapper w/ admin auth option

- packages/core/src/exports/index.ts
- packages/node/src/exports/index.ts
- packages/react/src/exports/index.ts
This PR ensures the types from the websocket utility changes are properly exported
> core, node, react: export ws types correctly

- packages/core/src/actions/getWalletOrderIds.ts
- packages/core/src/constants.ts
- packages/core/src/exports/actions.ts
- packages/core/src/exports/index.ts
This PR adds an admin action for fetching the order IDs associated with a wallet in accordance with https://github.com/renegade-fi/renegade/pull/802
This will be tested downstream of consumption in the internal bot server
> core: actions: admin get wallet order IDs action

- packages/core/src/utils/http.ts
This PR fixes the special-case `BigInt` JSON parsing for endpoints that return both floating-point and integer types to parse the JSON source directly into a BigInt, as opposed to the number type resulting from the "first round" of JSON parsing.
> core: utils: http: parse BigInt values directly from JSON source

- packages/core/src/constants.ts
- packages/core/src/exports/actions.ts
- packages/core/src/exports/index.ts
This PR exports the new admin wallet updates websocket route from the SDK (and fixes the exports of the "get order IDs for wallet" action)
> core: constants: export admin wallet updates ws route

- packages/core/src/actions/getOpenOrders.ts
- packages/core/src/actions/getOrderMetadata.ts
- packages/core/src/actions/getWalletOrderIds.ts
- packages/core/src/constants.ts
- packages/core/src/exports/actions.ts
- packages/core/src/exports/index.ts
- packages/core/src/types/order.ts
This PR brings the `getOpenOrders` and `getOrderMetadata` actions in sync w/ the new response shapes used by the relayer
> core: actions: getOpenOrders, getOrderMetadata: use new response shapes

- packages/react/src/hooks/useOrderBookWebSocket.ts
- packages/react/src/hooks/useOrderHistoryWebSocket.ts
- packages/react/src/hooks/useTaskHistoryWebSocket.ts
- packages/react/src/hooks/useWalletWebSocket.ts
- packages/react/tsconfig.build.json
This PR adjusts TypeScript configuration to allow for ES Modules to be imported using their default export, specifically in the `/react` subpackage. This allows us to remove non-standard `.default` from the `react-use-websocket` library which was causing build issues in some bundlers of consumers.
> react: allow importing default export from es module

- packages/core/CHANGELOG.md
- packages/core/package.json
- packages/node/CHANGELOG.md
- packages/node/package.json
- packages/react/CHANGELOG.md
- packages/react/package.json
- packages/test/CHANGELOG.md
- packages/test/package.json
- wasm/src/external_api/http.rs
This PR includes the blinder seed derived from a wallet seed so the relayer is able to verify this to prevent blinder frontrunning as described in https://github.com/renegade-fi/renegade/pull/811.
Tested locally, ensures that wallet is created when blinder seed is included in request, and fails to create when blinder seed is absent.
> wasm: include public blinder to create-wallet

- packages/core/src/types/token.ts
This PR modifies the `Token` class such that when searching for a token by it's mint or ticker, a `DEFAULT_TOKEN` will be returned if no token exists in the token mapping.
> core: return DEFAULT_TOKEN as fallback in Token

- packages/core/CHANGELOG.md
- packages/core/package.json
- packages/core/src/actions/getExternalMatchBundle.ts
- packages/core/src/constants.ts
- packages/core/src/createAuthConfig.ts
- packages/core/src/createConfig.ts
- packages/core/src/exports/actions.ts
- packages/core/src/exports/index.ts
- packages/core/src/types/externalOrder.ts
- packages/core/src/utils.d.ts
- packages/core/src/utils/http.ts
- packages/node/CHANGELOG.md
- packages/node/package.json
- packages/node/src/exports/index.ts
- packages/react/CHANGELOG.md
- packages/react/package.json
- packages/react/src/exports/index.ts
- packages/test/CHANGELOG.md
- packages/test/package.json
- wasm/src/external_api/auth/auth_helpers.rs
- wasm/src/external_api/http.rs
This PR adds the `getExternalMatchBundle` action to allow for parties external to the darkpool to match with parties internal to the darkpool. Internal parties are defined by those that have state committed into the protocol. Because this action interacts with a new server with separate API keys/secrets, the signature of the `postRelayerWithAuth` function was changed to allow for headers and auth key, to be passed in addition to url and body. The other HTTP helpers should follow this change as it is a more reusable abstraction.
Tested against testnet stack using local scripts.
> wasm, core, react, node: add action to request external match bundles

- packages/core/CHANGELOG.md
- packages/core/package.json
- packages/core/src/actions/getExternalMatchBundle.ts
- packages/core/src/types/externalOrder.ts
- packages/core/src/utils.d.ts
- packages/node/CHANGELOG.md
- packages/node/package.json
- packages/react/CHANGELOG.md
- packages/react/package.json
- packages/test/CHANGELOG.md
- packages/test/package.json
- wasm/src/external_api/http.rs
This PR allows external orders to be specified according to `quote_amount`, and also setting the `do_gas_estimation` flag to receive gas estimates in the response.. 
Tested that bundles are received against mainnet auth server.
> wasm, core: allow `quote_amount` and `do_gas_estimation` in external order

- packages/core/src/types/externalOrder.ts
- packages/core/src/types/match.ts
This PR adds fields to the response type of `getExternalMatchBundle` to be aligned with https://github.com/renegade-fi/renegade/pull/846.
Tested that each field exists in the response when fetching from testnet relayer.
> core: add fee details to external match bundle response

- packages/core/src/actions/assembleExternalQuote.ts
- packages/core/src/actions/getExternalMatchBundle.ts
- packages/core/src/actions/getExternalMatchQuote.ts
- packages/core/src/constants.ts
- packages/core/src/exports/actions.ts
- packages/core/src/exports/index.ts
- packages/core/src/types/externalMatch.ts
- packages/core/src/types/match.ts
- packages/core/src/utils.d.ts
- packages/core/src/utils/http.ts
- wasm/src/external_api/auth/auth_helpers.rs
- wasm/src/external_api/http.rs
- wasm/src/external_api/types.rs
- wasm/src/lib.rs
This PR adds two actions for:
- Fetching an external match quote from the relayer
- Assembling this external match quote into a settlement bundle
As well, this PR fixes an issue deserializing bigints in POST requests in an analogous way to the fix for GET requests.
-[x] I tested this flow locally using a typescript client I wrote
> core: actions: Add `getExternalMatchQuote` and `assembleExternalQuote` actions

- packages/core/src/actions/getExternalMatchBundle.ts
- packages/core/src/actions/getExternalMatchQuote.ts
- packages/core/src/types/externalMatch.ts
This PR makes the naming in `getExternalMatchQuote` consistent with `getExternalMatchBundle`.
> core: actions: getExternalMatchQuote: Use consistent parameter names

- packages/core/CHANGELOG.md
- packages/core/package.json
- packages/node/CHANGELOG.md
- packages/node/package.json
- packages/react/CHANGELOG.md
- packages/react/package.json
- packages/test/CHANGELOG.md
- packages/test/package.json
This PR bumps the versions for the `node` and `core` packages.
> packages: Bump version to 0.4.6 for `node` and `core`

- packages/core/src/constants.ts
- packages/core/src/exports/index.ts
- packages/core/src/types/token.ts
- packages/react/package.json
- packages/react/src/exports/index.ts
This PR updates the initialization of the `tokenMapping` constant and the properties of `Token` class.
Namely, the SDK now checks for the presence of a `TOKEN_MAPPING_URL` or `NEXT_PUBLIC_TOKEN_MAPPING_URL` environment variable, which, if present, results in the token mapping being fetched from the given URL.
The new token mapping fields - `supported_exchanges`, `chain_addresses`, and `logo_url` - have been added to the `Token` class, along with expected getters.
> core: token: fetch token mapping, use new format

- packages/core/src/exports/index.ts
- packages/core/src/types/token.ts
- packages/react/src/exports/index.ts
This PR packages the fetching & setting of the token mapping into a `loadTokenMapping` function that is exported, in case any clients want to refetch / reset the token mapping. This has been tested by running a simple node server that loads (and reloads) the token mapping after a change.
> core: token: export loadTokenMapping function

- packages/core/src/actions/getPriceFromPriceReporter.ts
- packages/core/src/exports/index.ts
- packages/core/src/types/token.ts
- packages/react/src/exports/index.ts
This PR updates the `DEFAULT_QUOTE` object to be richer (as expected by the frontend) and re-exports it for downstream consumption
> core: token: export DEFAULT_QUOTE

- packages/core/CHANGELOG.md
- packages/core/package.json
- packages/core/src/types/token.ts
- packages/node/CHANGELOG.md
- packages/node/package.json
- packages/react/CHANGELOG.md
- packages/react/package.json
- packages/test/CHANGELOG.md
- packages/test/package.json
This PR removes the top-level `await` from the token module, deferring the fetching of the token mapping to the consumer to prevent incompatibilities with top-level `await`s.
> core: token: no top-level fetch

- packages/core/CHANGELOG.md
- packages/core/package.json
- packages/core/src/types/token.ts
- packages/node/CHANGELOG.md
- packages/node/package.json
- packages/react/CHANGELOG.md
- packages/react/package.json
- packages/test/CHANGELOG.md
- packages/test/package.json
This PR fixes a bug wherein the token mapping is not formatted when reading it from an environment variable.
> core: token: format token mapping when reading from env var

- packages/core/src/actions/assembleExternalQuote.ts
- packages/core/src/utils.d.ts
- wasm/src/circuit_types/order.rs
- wasm/src/external_api/http.rs
This PR allows for an order to update in between quote and assembly. The only fields allowed to update are `baseAmount`, `quoteAmount`, and `minFillSize`.
> packages: actions: assembleExternalQuote: Allow updated order

- packages/core/src/createAuthConfig.ts
- packages/core/src/createConfig.ts
- packages/core/src/createExternalKeyConfig.ts
- packages/core/src/utils/http.ts
- packages/core/src/utils/websocket.ts
This PR adds a getter for the symmetric key for a config. This moves the logic for determining what symmetric key to authenticate a request with to the config.
> core: add symmetric key getter to config

- packages/core/src/actions/cancelOrder.ts
- packages/core/src/actions/createOrder.ts
- packages/core/src/actions/createOrderInMatchingPool.ts
- packages/core/src/actions/deposit.ts
- packages/core/src/actions/withdraw.ts
- packages/core/src/createAuthConfig.ts
- packages/core/src/createConfig.ts
- packages/core/src/utils.d.ts
- wasm/src/common/keychain.rs
- wasm/src/external_api/http.rs
- wasm/src/key_rotation.rs
- wasm/src/lib.rs
This PR implements keychain rotation for externally managed keys. It uses the Renegade key type to decide whether to rotate the key internally or use the public key provided by the SDK consumer. In both cases, it will increment the nonce if the public key has been rotated.
> wasm, core: implement keychain rotation for external key

- packages/core/src/actions/cancelOrder.ts
- packages/core/src/utils.d.ts
- wasm/src/external_api/http.rs
This PR allows externally managed wallets to cancel orders.
> wasm, core: impl external key cancel order action

- packages/core/src/actions/cancelOrder.ts
- packages/core/src/actions/createOrder.ts
- packages/core/src/actions/createOrderInMatchingPool.ts
- packages/core/src/utils.d.ts
- wasm/src/external_api/http.rs
This PR allows externally managed wallets to create orders.
> wasm, core: impl external key create order action

- packages/core/src/actions/cancelOrder.ts
- packages/core/src/actions/createOrder.ts
- packages/core/src/actions/createOrderInMatchingPool.ts
- packages/core/src/actions/withdraw.ts
- packages/core/src/utils.d.ts
- wasm/src/external_api/http.rs
- wasm/src/signature.rs
This PR allows externally managed keys to use the withdraw task. It creates helper functions to decide what signing function to use based on the key type.
> wasm, core: impl external key withdraw action

- packages/core/src/actions/cancelOrder.ts
- packages/core/src/actions/createOrder.ts
- packages/core/src/actions/createOrderInMatchingPool.ts
- packages/core/src/actions/deposit.ts
- packages/core/src/actions/getBackOfQueueWallet.ts
- packages/core/src/actions/getWalletId.ts
- packages/core/src/actions/withdraw.ts
- packages/core/src/createAuthConfig.ts
- packages/core/src/createConfig.ts
- packages/core/src/createExternalKeyConfig.ts
- packages/core/src/utils.d.ts
- packages/core/src/utils/http.ts
- wasm/Cargo.lock
- wasm/Cargo.toml
- wasm/src/external_api/http.rs
- wasm/src/lib.rs
- wasm/src/signature.rs
This PR implements the deposit task for external key configs. In doing so, a discriminated union type `RenegadeConfig` was created to allow for type narrowing based on `renegadeKeyType`, and helper functions were updated to ingest this change.
> wasm, core: impl external key deposit action

- packages/core/src/actions/cancelOrder.ts
- packages/core/src/actions/createOrder.ts
- packages/core/src/actions/deposit.ts
- packages/core/src/actions/withdraw.ts
- packages/core/src/utils.d.ts
- wasm/src/external_api/http.rs
- wasm/src/key_rotation.rs
- wasm/src/signature.rs
This PR makes changes to how we determine the key type of a wallet. We enforce in Javascript that externally managed keys must provide a sign callback and internally managed keys must provide a seed. This obviates the need to pass `key_type` as a parameter as we can now rely on the presence of either of these functions to branch.
> wasm, core: remove need for key_type in Rust context

- packages/core/src/actions/getPkRoot.ts
- packages/core/src/exports/index.ts
- packages/core/src/utils.d.ts
- packages/node/src/exports/index.ts
- wasm/src/lib.rs
This PR modifies the existing `getPkRoot` action to use the public key in an external config if provided. This is primarly used to retrieve the witness value for permit2 signatures, which is the non-rotated `pkRoot` scalars. Also exports `createExternalConfig` for testing.
> wasm, core: impl external key get pk scalars

- wasm/src/signature.rs
This PR removes prehasing of the message when using an external signer.
> wasm: do not prehash message when using external signer

- packages/core/src/actions/getTaskHistory.ts
- packages/core/src/actions/waitForTaskCompletionWs.ts
- packages/core/src/utils/websocket.ts
- packages/core/src/utils/websocketWaiter.ts
This PR modifies types to make waitForTaskCompletionWs compatible with ExternalConfigs.
> core: impl await task completion for externally managed keys

- packages/core/src/actions/lookupWallet.ts
- packages/core/src/utils.d.ts
- wasm/src/external_api/find_wallet.rs
- wasm/src/external_api/mod.rs
This PR makes the lookup wallet action compatible with externally managed keys. Similarly to create wallet, the Rust util function was broken out into a separate function since there is no overlap with the internally manged key version.
> wasm, core: impl external key lookup wallet

- packages/core/src/actions/createWallet.ts
- packages/core/src/actions/getWalletFromRelayer.ts
- packages/core/src/actions/lookupWallet.ts
- packages/core/src/actions/waitForWalletIndexing.ts
- packages/core/src/exports/index.ts
- packages/core/src/utils.d.ts
- wasm/src/errors.rs
- wasm/src/external_api/create_wallet.rs
- wasm/src/external_api/find_wallet.rs
- wasm/src/external_api/mod.rs
This PR adds makes the create wallet action compatible with external key types. It creates a new helper in the Rust utils since there is no overlap in parameters between creating internal wallets vs. external wallets.
> wasm, core: impl external key create wallet

- packages/core/src/actions/refreshWallet.ts
This PR makes the refresh wallet task compatible with externally managed wallets.
> wasm, core: impl external key refresh wallet

- packages/core/src/createExternalKeyConfig.ts
This PR adds setter and getter functions for the public key in ExternalConfig, to allow SDK consumers to set the public key (usually after key rotation) without having to reinstantiate an external config.
> core: add public key getter and setter fns to external config

- packages/core/CHANGELOG.md
- packages/core/package.json
- packages/core/src/utils.d.ts
- packages/node/CHANGELOG.md
- packages/node/package.json
- packages/react/CHANGELOG.md
- packages/react/package.json
- packages/test/CHANGELOG.md
- packages/test/package.json
- wasm/src/external_api/http.rs
- wasm/src/key_rotation.rs
- wasm/src/signature.rs
This PR fixes an issue where the rotated keychain was used to derive a signing key that was resulting in invalid wallet update signatures. To do so, the correct signing key is returned by `handle_keychain_rotation`, and is used as the signing key for internal wallets.
> wasm: sign wallet comm using correct signing key

- packages/core/src/utils/http.ts
This PR updates the `getPathFromUrl` helper used in making authenticated requests to the relayer to include the query string in the path. As of https://github.com/renegade-fi/renegade/pull/884, this is now expected to be present for authenticating requests that include query strings.
I tested this against a local relayer (running https://github.com/renegade-fi/renegade/pull/884) and using a local frontend that ran with a canary release of these changes. I asserted that the task history endpoint could be successfully invoked when the `task_history_len` parameter was set.
> core: utils: http: include query string in path for auth

- packages/core/src/utils/http.ts
This PR wraps the `postRelayerRaw` JSON parse in a try-catch to properly handle cases in which no body or a string body is returned.
> packages: core: http: Return raw response data if JSON cannot parse

- packages/node/src/actions/executeWithdrawal.ts
This PR updates the `executeWithdrawal` action to be compatible with both external configs and internal configs.
> node: Accept external key config in executeWithdrawal action

- packages/node/CHANGELOG.md
- packages/node/package.json
- packages/node/src/actions/executeDeposit.ts
This PR implements the [suggested](https://viem.sh/docs/contract/writeContract.html#usage) pattern of pairing `simulateContract` with `writeContract` to validate that the contract write will execute without errors. This fixes an issue we saw with sending approval transactions on testnet.
The deposit transaction is attempted even if the transaction receipt is not received. This is because we often miss transaction receipts in testnet.
This replaces helper functions generated by `@wagmi/cli`.
> node: Use simulate + write contract pattern for approval tx

- packages/core/CHANGELOG.md
- packages/core/package.json
- packages/core/src/actions/getOrderHistory.ts
- packages/core/src/actions/getTaskHistory.ts
- packages/core/src/chains/defaults.ts
- packages/core/src/createConfig.ts
- packages/core/src/createExternalKeyConfig.ts
- packages/core/src/exports/index.ts
- packages/core/src/utils.d.ts
- packages/node/CHANGELOG.md
- packages/node/package.json
- packages/react/CHANGELOG.md
- packages/react/package.json
- packages/react/src/exports/index.ts
- packages/test/CHANGELOG.md
- packages/test/package.json
- packages/test/src/testConfig.ts
This PR modifies the `getOrderHistory` and `getTaskHistory` actions to use the Historical State Engine as the default server to fetch from. The URL is set based on the chain ID that the consumer must now set to create a config, which is a breaking change. In a future PR, this chain ID will be used to derive default values for other config parameters (e.g. relayer base URL, websocket URL, etc.). This is done in a type safe way—consumers will see suggestions when defining chain ID and will also have access to a utility function `isSupportedChainId` to type narrow the value (e.g. when using an environment variable).
If the need to configure the HSE base URL arises that change can be made, but for now we use the default to reduce complexity.
> core: Use HSE in order history and task history actions

- packages/core/src/actions/assembleExternalQuote.ts
- packages/core/src/actions/getExternalMatchBundle.ts
- packages/core/src/constants.ts
- packages/core/src/types/externalMatch.ts
This PR tweaks the parameters to the `assembleExternalQuote` and `getExternalMatchBundle` actions to accept options for requesting gas sponsorship through the auth server.
This has been tested against the testnet stack.
> core: actions: assembleExternalQuote, getExternalMatchBundle: gas sponsorship options

- packages/core/src/actions/assembleExternalQuote.ts
- packages/core/src/actions/getExternalMatchBundle.ts
- packages/core/src/types/externalMatch.ts
This PR adds a separate `ExternalMatchResponse` type which mirrors the response shape returned by the auth server.
This was tested by invoking external matches against the testnet stack
> core: types: externalMatch: add ExternalMatchResponse type

- examples/external-match/CHANGELOG.md
- examples/external-match/package.json
- examples/gas-sponsorship/CHANGELOG.md
- examples/gas-sponsorship/package.json
- packages/core/CHANGELOG.md
- packages/core/package.json
- packages/core/src/clients/price-reporter/client.ts
- packages/core/src/clients/price-reporter/error.ts
- packages/core/src/exports/index.ts
- packages/node/CHANGELOG.md
- packages/node/package.json
- packages/react/CHANGELOG.md
- packages/react/package.json
- packages/test/CHANGELOG.md
- packages/test/package.json
- pnpm-lock.yaml
This PR defines a price reporter client that does not depend on a `Config` or `RenegadeConfig` object. Such a client is required in the bot server, and is also good practice to decouple hitting the price reporter from the config object meant for interacting with the Relayer API.
> core: define standalone PriceReporterClient

- examples/in-kind-gas-sponsorship/README.md
- examples/in-kind-gas-sponsorship/index.ts
- examples/native-eth-gas-sponsorship/README.md
- examples/native-eth-gas-sponsorship/index.ts
- packages/core/src/actions/getExternalMatchBundle.ts
- packages/core/src/actions/getExternalMatchQuote.ts
- packages/core/src/constants.ts
- pnpm-lock.yaml
This PR updates the SDK to using the `omit_gas_sponsorship` param instead of the now-deprecated `use_gas_sponsorship`.
> packages: core: use omit_gas_sponsorship query param

- packages/react/src/hooks/useOrderHistoryWebSocket.ts
- packages/react/src/hooks/useTaskHistoryWebSocket.ts
- packages/react/src/hooks/useWalletWebSocket.ts
This PR temporarily disables unsubscribing from topics in WebSockets. Because each hook invocation uses the same WebSocket connection, we cannot simply unsubscribe on unmount as a different invocation of the same hook may be using the connection. Therefore, we need a layer that keeps track of hook invocations and unsubscribes from topics iff there are no more hooks using the connection. This is not urgent, so we are reverting to old behavior for the time being.
> react: temp disable unsubscribing ws topics

- examples/external-match/CHANGELOG.md
- examples/external-match/package.json
- examples/in-kind-gas-sponsorship/CHANGELOG.md
- examples/in-kind-gas-sponsorship/package.json
- examples/native-eth-gas-sponsorship/CHANGELOG.md
- examples/native-eth-gas-sponsorship/package.json
- packages/core/CHANGELOG.md
- packages/core/package.json
- packages/core/src/types/token.ts
- packages/node/CHANGELOG.md
- packages/node/package.json
- packages/react/CHANGELOG.md
- packages/react/package.json
- packages/test/CHANGELOG.md
- packages/test/package.json
This PR adds the TS analog of the `convert_to_decimal` method that exists [in Rust](https://github.com/renegade-fi/renegade/blob/4ddd79352aaab61328e1437e2b85da47c5ddd6ac/common/src/types/token.rs#L190).
> core: token: add convert to decimal helper

- packages/core/src/constants.ts
- packages/core/src/utils/http.ts
- tsconfig.base.json
This PR adds an SDK version header to the typescript SDK requests. We use the `@renegade-fi/core` version for this.
> core: utils: http: Add `x-renegade-sdk-version` to headers

- examples/external-match/CHANGELOG.md
- examples/external-match/package.json
- examples/in-kind-gas-sponsorship/CHANGELOG.md
- examples/in-kind-gas-sponsorship/package.json
- examples/native-eth-gas-sponsorship/CHANGELOG.md
- examples/native-eth-gas-sponsorship/package.json
- packages/core/CHANGELOG.md
- packages/core/package.json
- packages/core/src/utils.d.ts
- packages/core/src/version.ts
- packages/node/CHANGELOG.md
- packages/node/package.json
- packages/react/CHANGELOG.md
- packages/react/package.json
- packages/test/CHANGELOG.md
- packages/test/package.json
- wasm/Cargo.lock
- wasm/Cargo.toml
- wasm/src/external_api/http.rs
- wasm/src/external_api/types.rs
This PR removes the `gas_sponsorship_info` field from the `AssembleExternalMatchRequest`, as it is no longer needed by the API.
> wasm: external_api: remove sponsorship info from assembly req

- examples/external-match/CHANGELOG.md
- examples/external-match/package.json
- examples/in-kind-gas-sponsorship/CHANGELOG.md
- examples/in-kind-gas-sponsorship/package.json
- examples/native-eth-gas-sponsorship/CHANGELOG.md
- examples/native-eth-gas-sponsorship/package.json
- packages/core/CHANGELOG.md
- packages/core/package.json
- packages/core/src/utils/websocketWaiter.ts
- packages/core/src/version.ts
- packages/node/CHANGELOG.md
- packages/node/package.json
- packages/react/CHANGELOG.md
- packages/react/package.json
- packages/test/CHANGELOG.md
- packages/test/package.json
This PR fixes up the `websocketWaiter` utility to properly catch errors thrown in the `prefetch` function. Since this is a Promise that is not directly `awaited`, any errors thrown in it would not be caught by `try/catch` blocks wrapping the top-level `websocketWaiter` Promise.
> core: utils: websocketWaiter: catch prefetch errors

- examples/external-match/CHANGELOG.md
- examples/external-match/package.json
- examples/in-kind-gas-sponsorship/CHANGELOG.md
- examples/in-kind-gas-sponsorship/package.json
- examples/malleable-external-match/CHANGELOG.md
- examples/malleable-external-match/package.json
- examples/native-eth-gas-sponsorship/CHANGELOG.md
- examples/native-eth-gas-sponsorship/package.json
- packages/core/CHANGELOG.md
- packages/core/package.json
- packages/core/src/actions/triggerRelayerSnapshot.ts
- packages/core/src/constants.ts
- packages/core/src/exports/actions.ts
- packages/core/src/exports/index.ts
- packages/core/src/utils.d.ts
- packages/core/src/version.ts
- packages/node/CHANGELOG.md
- packages/node/package.json
- packages/price-reporter/CHANGELOG.md
- packages/price-reporter/package.json
- packages/react/CHANGELOG.md
- packages/react/package.json
- packages/test/CHANGELOG.md
- packages/test/package.json
- packages/token/CHANGELOG.md
- packages/token/package.json
- packages/token/src/index.ts
This PR adds a `triggerRelayerSnapshot` action for those with admin access to the relayer they configured the SDK with.
This was tested internally against our own testnet relayer.
> packages: core: actions: triggerRelayerSnapshot action

- examples/external-match/CHANGELOG.md
- examples/external-match/package.json
- examples/in-kind-gas-sponsorship/CHANGELOG.md
- examples/in-kind-gas-sponsorship/package.json
- examples/malleable-external-match/CHANGELOG.md
- examples/malleable-external-match/package.json
- examples/native-eth-gas-sponsorship/CHANGELOG.md
- examples/native-eth-gas-sponsorship/package.json
- packages/core/CHANGELOG.md
- packages/core/package.json
- packages/core/src/actions/updateOrder.ts
- packages/core/src/utils.d.ts
- packages/core/src/version.ts
- packages/node/CHANGELOG.md
- packages/node/package.json
- packages/node/src/clients/relayer/index.ts
- packages/node/src/clients/renegade/admin.ts
- packages/node/src/clients/renegade/base.ts
- packages/price-reporter/CHANGELOG.md
- packages/price-reporter/package.json
- packages/react/CHANGELOG.md
- packages/react/package.json
- packages/test/CHANGELOG.md
- packages/test/package.json
- packages/token/CHANGELOG.md
- packages/token/package.json
- wasm/src/external_api/http.rs
This PR adds updateOrder, getWalletId, getTaskQueuePaused methods to the RenegadeClient. The `updateOrder` path had to be updated to be compatible with external keychains, this was done by copying code from `placeOrder` path as the signature generation steps are the same.
> wasm, core: make update order path compatible with external keychains

- examples/external-match/CHANGELOG.md
- examples/external-match/package.json
- examples/in-kind-gas-sponsorship/CHANGELOG.md
- examples/in-kind-gas-sponsorship/package.json
- examples/malleable-external-match/CHANGELOG.md
- examples/malleable-external-match/package.json
- examples/native-eth-gas-sponsorship/CHANGELOG.md
- examples/native-eth-gas-sponsorship/package.json
- packages/core/CHANGELOG.md
- packages/core/package.json
- packages/core/src/utils/websocket.ts
- packages/core/src/utils/websocketWaiter.ts
- packages/core/src/version.ts
- packages/node/CHANGELOG.md
- packages/node/package.json
- packages/node/src/clients/renegade/base.ts
- packages/price-reporter/CHANGELOG.md
- packages/price-reporter/package.json
- packages/react/CHANGELOG.md
- packages/react/package.json
- packages/test/CHANGELOG.md
- packages/test/package.json
- packages/token/CHANGELOG.md
- packages/token/package.json
This PR filters default structs from the get-wallet response by default. We also handle errors thrown from tasks that fail immediately when prefetching their status.
> core, node: filter defaults when fetching wallet, catch error in prefetch

- examples/external-match/CHANGELOG.md
- examples/external-match/package.json
- examples/in-kind-gas-sponsorship/CHANGELOG.md
- examples/in-kind-gas-sponsorship/package.json
- examples/malleable-external-match/CHANGELOG.md
- examples/malleable-external-match/package.json
- examples/native-eth-gas-sponsorship/CHANGELOG.md
- examples/native-eth-gas-sponsorship/package.json
- packages/core/CHANGELOG.md
- packages/core/package.json
- packages/core/src/constants.ts
- packages/core/src/version.ts
- packages/node/CHANGELOG.md
- packages/node/package.json
- packages/price-reporter/CHANGELOG.md
- packages/price-reporter/package.json
- packages/react/CHANGELOG.md
- packages/react/package.json
- packages/test/CHANGELOG.md
- packages/test/package.json
- packages/token/CHANGELOG.md
- packages/token/package.json
This PR migrates the URLs of chain-specific resources (relayer, auth server) to the new naming convention.
I asserted that these are the correct URLs by copying them into Postman and invoking the associated resource's healthcheck endpoint.
> core: constants: update chain-specific URLs

- packages/core/src/types/malleableMatch.ts
This PR sets the `tx.value` field correctly for native ETH sells.
> core: types: malleableMatch: Set `tx.value` for native eth sell

- examples/external-match/CHANGELOG.md
- examples/external-match/package.json
- examples/in-kind-gas-sponsorship/CHANGELOG.md
- examples/in-kind-gas-sponsorship/package.json
- examples/malleable-external-match/CHANGELOG.md
- examples/malleable-external-match/package.json
- examples/native-eth-gas-sponsorship/CHANGELOG.md
- examples/native-eth-gas-sponsorship/package.json
- packages/core/CHANGELOG.md
- packages/core/package.json
- packages/core/src/types/wallet.ts
- packages/core/src/version.ts
- packages/node/CHANGELOG.md
- packages/node/package.json
- packages/price-reporter/CHANGELOG.md
- packages/price-reporter/package.json
- packages/price-reporter/src/client.ts
- packages/price-reporter/src/constants.ts
- packages/react/CHANGELOG.md
- packages/react/package.json
- packages/test/CHANGELOG.md
- packages/test/package.json
- packages/token/CHANGELOG.md
- packages/token/package.json
- packages/token/src/index.ts
This PR sets the exchange to "renegade" when fetching prices using `getPrice`.
> price-reporter, core, token: use canonical exchange for getPrice

- examples/external-match/CHANGELOG.md
- examples/external-match/package.json
- examples/in-kind-gas-sponsorship/CHANGELOG.md
- examples/in-kind-gas-sponsorship/package.json
- examples/malleable-external-match/CHANGELOG.md
- examples/malleable-external-match/package.json
- examples/native-eth-gas-sponsorship/CHANGELOG.md
- examples/native-eth-gas-sponsorship/package.json
- packages/core/CHANGELOG.md
- packages/core/package.json
- packages/core/src/chains/defaults.ts
- packages/core/src/exports/index.ts
- packages/core/src/version.ts
- packages/node/CHANGELOG.md
- packages/node/package.json
- packages/price-reporter/CHANGELOG.md
- packages/price-reporter/package.json
- packages/price-reporter/src/client.ts
- packages/react/CHANGELOG.md
- packages/react/package.json
- packages/test/CHANGELOG.md
- packages/test/package.json
- packages/token/CHANGELOG.md
- packages/token/package.json
This PR modifies the deprecated `getBinancePrice` static method to use the `renegade` exchange price topic. In a future PR, we should migrate off of static methods that assume an environment variable is set.
This is safe because all callsites of `getBinancePrice` actually want the canonical exchange price.
> price-reporter: override binance price query

- examples/external-match/CHANGELOG.md
- examples/external-match/package.json
- examples/in-kind-gas-sponsorship/CHANGELOG.md
- examples/in-kind-gas-sponsorship/package.json
- examples/malleable-external-match/CHANGELOG.md
- examples/malleable-external-match/package.json
- examples/native-eth-gas-sponsorship/CHANGELOG.md
- examples/native-eth-gas-sponsorship/package.json
- packages/core/CHANGELOG.md
- packages/core/package.json
- packages/core/src/chains/defaults.ts
- packages/core/src/constants.ts
- packages/core/src/exports/index.ts
- packages/core/src/version.ts
- packages/node/CHANGELOG.md
- packages/node/package.json
- packages/price-reporter/CHANGELOG.md
- packages/price-reporter/package.json
- packages/react/CHANGELOG.md
- packages/react/package.json
- packages/test/CHANGELOG.md
- packages/test/package.json
- packages/token-nextjs/CHANGELOG.md
- packages/token-nextjs/package.json
- packages/token-nextjs/src/index.ts
- packages/token/CHANGELOG.md
- packages/token/package.json
- pnpm-lock.yaml
This PR updates the `token-nextjs` package to be multi-chain capable. Concretely, this means it now adds a remap for each of the potential environment variables (`NEXT_PUBLIC_${chain}_TOKEN_MAPPING`). This required adding an enum for env-agnostic chain names, and also having the module expect a `NEXT_PUBLIC_CHAIN_ENVIRONMENT` env var to be set, which is one of the `Environment` values (`testnet`, `mainnet`).
> packages: core, token-nextjs: add multi-chain remaps in NextJS context

- examples/external-match/CHANGELOG.md
- examples/external-match/package.json
- examples/in-kind-gas-sponsorship/CHANGELOG.md
- examples/in-kind-gas-sponsorship/package.json
- examples/malleable-external-match/CHANGELOG.md
- examples/malleable-external-match/package.json
- examples/native-eth-gas-sponsorship/CHANGELOG.md
- examples/native-eth-gas-sponsorship/package.json
- packages/core/CHANGELOG.md
- packages/core/package.json
- packages/core/src/chains/defaults.ts
- packages/core/src/constants.ts
- packages/core/src/utils.d.ts
- packages/core/src/version.ts
- packages/node/CHANGELOG.md
- packages/node/package.json
- packages/price-reporter/CHANGELOG.md
- packages/price-reporter/package.json
- packages/react/CHANGELOG.md
- packages/react/package.json
- packages/test/CHANGELOG.md
- packages/test/package.json
- packages/token-nextjs/CHANGELOG.md
- packages/token-nextjs/package.json
- packages/token/CHANGELOG.md
- packages/token/package.json
- packages/token/src/index.ts
This PR adds config entries for the Base mainnet deployment.
Testing of all the actions on Base mainnet can be deferred, this is worth releasing so that consumers of the SDK can access these config entries in order to integrate properly.
> packages: core: add base mainnet config

- examples/external-match/CHANGELOG.md
- examples/external-match/package.json
- examples/in-kind-gas-sponsorship/CHANGELOG.md
- examples/in-kind-gas-sponsorship/package.json
- examples/malleable-external-match/CHANGELOG.md
- examples/malleable-external-match/package.json
- examples/native-eth-gas-sponsorship/CHANGELOG.md
- examples/native-eth-gas-sponsorship/package.json
- packages/core/CHANGELOG.md
- packages/core/package.json
- packages/core/src/chains/defaults.ts
- packages/core/src/version.ts
- packages/node/CHANGELOG.md
- packages/node/package.json
- packages/price-reporter/CHANGELOG.md
- packages/price-reporter/package.json
- packages/react/CHANGELOG.md
- packages/react/package.json
- packages/test/CHANGELOG.md
- packages/test/package.json
- packages/token-nextjs/CHANGELOG.md
- packages/token-nextjs/package.json
- packages/token-nextjs/src/index.ts
- packages/token/CHANGELOG.md
- packages/token/package.json
This PR gets the `token-nextjs` package into a usable state by ensuring that it properly utilizes the designated environment variables. We can't index into `process.env` client-side because NextJS will find-and-replace all `process.env.NEXT_PUBLIC_*` occurrences w/ the given variables, so we make sure to use this access pattern.
> packages: core, token-nextjs: fix improper env var usage

- examples/malleable-external-match/CHANGELOG.md
- examples/malleable-external-match/package.json
- packages/price-reporter/CHANGELOG.md
- packages/price-reporter/package.json
- packages/price-reporter/src/client.ts
- packages/price-reporter/src/constants.ts
- packages/token-nextjs/CHANGELOG.md
- packages/token-nextjs/package.json
- packages/token/CHANGELOG.md
- packages/token/package.json
- packages/token/src/index.ts
This PR adds two new methods to the `PriceReporterClient`, which fetch the price for a `Token`, expecting its `chain` to be set. This allows us to construct the correct quote token address for the price topic that we request from the price reporter.
> packages: price-reporter: expose chain-specific token price getters

- examples/external-match/CHANGELOG.md
- examples/external-match/package.json
- examples/in-kind-gas-sponsorship/CHANGELOG.md
- examples/in-kind-gas-sponsorship/package.json
- examples/malleable-external-match/CHANGELOG.md
- examples/malleable-external-match/package.json
- examples/native-eth-gas-sponsorship/CHANGELOG.md
- examples/native-eth-gas-sponsorship/package.json
- packages/core/CHANGELOG.md
- packages/core/package.json
- packages/core/src/chains/defaults.ts
- packages/core/src/version.ts
- packages/node/CHANGELOG.md
- packages/node/package.json
- packages/price-reporter/CHANGELOG.md
- packages/price-reporter/package.json
- packages/react/CHANGELOG.md
- packages/react/package.json
- packages/test/CHANGELOG.md
- packages/test/package.json
- packages/token-nextjs/CHANGELOG.md
- packages/token-nextjs/package.json
- packages/token/CHANGELOG.md
- packages/token/package.json
This PR adds an `ENV_AGNOSTIC_CHAINS.Base` case to the `ENVIRONMENT.Mainnet` branch of the `chainIdFromEnvAndName` helper.
> core: chains: add Base case for chainIdFromEnvAndName

- packages/core/src/createConfig.ts
- packages/react/src/hydrate.ts
This PR adds the chain ID field to the internal state of the config object. This is necessary to provide a stable reference to the chain used to sign in, as the client may switch chains (for example during the bridge and deposit flow).
> core: add chain id to config state

- packages/token-nextjs/CHANGELOG.md
- packages/token-nextjs/package.json
This PR sets `sideEffects: true` for the `token-nextjs` package, so that bundlers know not to tree-shake it if it is imported but unused.
> packages: token-nextjs: set sideEffects=true

- packages/react/src/exports/index.ts
- packages/react/src/hooks/useIsIndexed.ts
- packages/react/src/hooks/useOrderHistoryWebSocket.ts
- packages/react/src/hooks/useTaskHistoryWebSocket.ts
- packages/react/src/hooks/useWalletId.ts
- packages/react/src/hooks/useWalletWebSocket.ts
This PR ensures websocket topics are subscribed to only after the wallet has been indexed in the relayer. Previously, this was handled by the status field in the config. We have since decoupled the indexed state of a wallet from the relayer so we must check for this per websocket hook.
> react: ensure ws topic subscription happens after indexing

- packages/core/CHANGELOG.md
- packages/core/package.json
- packages/core/src/actions/getWalletNullifier.ts
- packages/core/src/exports/actions.ts
- packages/core/src/exports/index.ts
- packages/core/src/utils.d.ts
- packages/core/src/version.ts
- packages/node/CHANGELOG.md
- packages/node/package.json
- packages/node/src/clients/renegade/base.ts
- packages/price-reporter/CHANGELOG.md
- packages/price-reporter/package.json
- packages/react/CHANGELOG.md
- packages/react/package.json
- packages/test/CHANGELOG.md
- packages/test/package.json
- packages/token-nextjs/CHANGELOG.md
- packages/token-nextjs/package.json
- packages/token/CHANGELOG.md
- packages/token/package.json
- wasm/src/circuit_types/wallet.rs
- wasm/src/common/types.rs
- wasm/src/external_api/http.rs
- wasm/src/external_api/mod.rs
- wasm/src/external_api/wallet_utils.rs
This PR adds an action for computing the nullifier of the current back-of-queue wallet.
> wasm, actions: computeWalletNullifier action

- packages/core/CHANGELOG.md
- packages/core/package.json
- packages/core/src/actions/getWalletNullifier.ts
- packages/core/src/version.ts
- packages/node/CHANGELOG.md
- packages/node/package.json
- packages/price-reporter/CHANGELOG.md
- packages/price-reporter/package.json
- packages/react/CHANGELOG.md
- packages/react/package.json
- packages/test/CHANGELOG.md
- packages/test/package.json
- packages/token-nextjs/CHANGELOG.md
- packages/token-nextjs/package.json
- packages/token/CHANGELOG.md
- packages/token/package.json
This PR fixes the return type of the new `getWalletNullifier` action to be a `bigint`. It was incorrectly set to `boolean` as a vestige of when the method would check if the nullifier was spent onchain.
> core: actions: getWalletNullifier: fix return type

- biome.json
- package.json
- packages/core/src/actions/payFees.ts
- packages/core/src/query/utils.ts
- packages/core/src/utils/cookie.ts
- packages/core/src/utils/deepEqual.ts
- packages/core/src/utils/http.ts
- packages/node/src/utils/permit2.ts
- packages/react/src/hooks/useConfig.ts
- packages/react/src/hydrate.ts
- pnpm-lock.yaml
This PR fixes lint errors so CI passes. Most were due to suppressions of code directly copied from the wagmi codebase. In the near future, we will deprecate the @renegade-fi/react package entirely, as it does not provide meaningful, react-specific helpers on top of `@renegade-fi/core` (all hooks have been re-implemented in https://github.com/renegade-fi/renegade-frontend).
> chore: fix lint

- packages/core/src/createConfig.ts
- packages/core/src/createExternalKeyConfig.ts
- packages/core/src/logging/logger.ts
- packages/core/src/logging/types.ts
This PR adds an interface for a logger that consumers can provide to listen for log events at a given level. In the next PR we will replace instances of `console.log` by invoking this logger.
> core: add logger type

- package.json
- packages/core/CHANGELOG.md
- packages/core/package.json
- packages/core/src/version.ts
- packages/external-match/CHANGELOG.md
- packages/external-match/package.json
- packages/node/CHANGELOG.md
- packages/node/package.json
- packages/price-reporter/CHANGELOG.md
- packages/price-reporter/package.json
- packages/react/CHANGELOG.md
- packages/react/package.json
- packages/token-nextjs/CHANGELOG.md
- packages/token-nextjs/package.json
- packages/token/CHANGELOG.md
- packages/token/package.json
- packages/types/CHANGELOG.md
- packages/types/package.json
- pnpm-lock.yaml
This PR pins dependencies listed as compromised [here](https://github.com/debug-js/debug/issues/1005#issuecomment-3266868187) to versions that are not the compromised versions _and_ the same versions that were already in the lockfile. This is to avoid pulling in new versions. 
Current versions were found by running
`pnpm why chalk strip-ansi color-convert color-name is-core-module error-ex has-ansi`
> chore: pin to safe versions
