packages/core/src/actions/createWallet.ts
packages/core/src/actions/lookupWallet.ts

This PR handles errors when waiting for lookup-wallet and create-wallet task completion gracefully.

core: Handle lookup/create wallet errors gracefully

---

packages/core/src/actions/createWallet.ts
packages/core/src/actions/lookupWallet.ts
packages/core/src/index.ts
packages/node/package.json
packages/node/src/actions/connect.ts
packages/node/src/actions/createWallet.ts
packages/node/src/actions/lookupWallet.ts
packages/node/src/index.ts
pnpm-lock.yaml

This PR separates wallet connection logic for different environments (web vs. node).

core, node: Add node specific connect function

---

packages/core/src/createConfig.ts
packages/core/src/hydrate.ts

This PR adds a function to `Config` object that allows for users to enable/disable state persistence.

core: Add function to reinitialize store if user does not want persistence

---

packages/core/src/actions/createWallet.ts

This PR fixes a log in `create-wallet` action

core: fix create wallet log

---

packages/core/src/actions/assignOrder.ts
packages/core/src/constants.ts
packages/core/src/exports/actions.ts
packages/core/src/utils/http.ts

This PR creates an action for assigning an order to a matching pool using the admin API. This will be tested via consumption in our internal dashboard app

core: actions: assign order to matching pool action

---

package.json
packages/core/CHANGELOG.md
packages/core/package.json
packages/core/src/actions/cancelOrder.ts
packages/core/src/actions/cancelOrderRequest.ts
packages/core/src/actions/createOrder.ts
packages/core/src/actions/createOrderInMatchingPool.ts
packages/core/src/actions/createOrderRequest.ts
packages/core/src/actions/deposit.ts
packages/core/src/actions/depositRequest.ts
packages/core/src/actions/payFees.ts
packages/core/src/actions/reconnect.ts
packages/core/src/actions/refreshWallet.ts
packages/core/src/actions/updateOrder.ts
packages/core/src/actions/waitForTaskCompletion.ts
packages/core/src/actions/withdraw.ts
packages/core/src/actions/withdrawRequest.ts
packages/core/src/hydrate.ts
packages/node/CHANGELOG.md
packages/node/package.json
packages/react/CHANGELOG.md
packages/react/package.json
packages/react/src/hydrate.ts
packages/test/CHANGELOG.md
packages/test/package.json
pnpm-lock.yaml

This PR removes wallet data from console logs that existed for debugging purposes.

chore: remove debug logs

---

packages/core/CHANGELOG.md
packages/core/package.json
packages/core/src/actions/createOrder.ts
packages/core/src/actions/createOrderInMatchingPool.ts
packages/core/src/actions/updateOrder.ts
packages/node/CHANGELOG.md
packages/node/package.json
packages/react/CHANGELOG.md
packages/react/package.json
packages/test/CHANGELOG.md
packages/test/package.json

This PR sets defaults for the `worstCasePrice` and `minFillSize` in the various actions to create orders.

sdk: set default worst case price and min fill size

---

packages/react/CHANGELOG.md
packages/react/package.json
packages/react/src/hooks/useOrderBookWebSocket.ts
packages/react/src/hooks/useOrderHistoryWebSocket.ts
packages/react/src/hooks/useTaskHistoryWebSocket.ts
packages/react/src/hooks/useWalletWebSocket.ts

This PR fixes imports in helper hooks in the `react` package.

react: fix useWebsocket import

---

packages/core/CHANGELOG.md
packages/core/package.json
packages/node/CHANGELOG.md
packages/node/package.json
packages/react/CHANGELOG.md
packages/react/package.json
packages/test/CHANGELOG.md
packages/test/package.json

This PR bumps the versions of the TS SDK packages to include the quote/assemble path.

packages: Bump versions

---

packages/core/src/actions/getOrderHistory.ts
packages/core/src/actions/payFees.ts

core: impl get order + pay fees for external keys

---

packages/core/src/utils.d.ts
packages/node/src/actions/generateWalletSecrets.ts
packages/node/src/exports/index.ts
wasm/src/common/derivation.rs
wasm/src/generation.rs
wasm/src/helpers.rs
wasm/src/lib.rs

This PR adds the script used for wallet key generation using a signing callback.

wasm, core, node: impl external wallet key generation script

---

packages/core/CHANGELOG.md
packages/core/package.json
packages/node/CHANGELOG.md
packages/node/package.json
packages/react/CHANGELOG.md
packages/react/package.json
packages/test/CHANGELOG.md
packages/test/package.json

chore: version packages

---

packages/core/CHANGELOG.md
packages/core/package.json
packages/core/src/actions/getTaskQueuePaused.ts
packages/core/src/constants.ts
packages/core/src/exports/actions.ts
packages/core/src/utils.d.ts
packages/node/CHANGELOG.md
packages/node/package.json
packages/react/CHANGELOG.md
packages/react/package.json
packages/test/CHANGELOG.md
packages/test/package.json

This PR creates an action for the [new task queue paused API](https://github.com/renegade-fi/renegade/pull/891).

core: actions: getTaskQueuePaused action

---

.gitignore
examples/README.md
examples/external-match/.env.example
examples/external-match/README.md
examples/external-match/index.ts
examples/external-match/package.json
examples/gas-sponsorship/.env.example
examples/gas-sponsorship/README.md
examples/gas-sponsorship/index.ts
examples/gas-sponsorship/package.json
packages/core/src/actions/assembleExternalQuote.ts
packages/core/src/actions/getExternalMatchBundle.ts
packages/core/src/constants.ts
packages/core/src/types/externalMatch.ts
packages/core/src/utils.d.ts
pnpm-lock.yaml
pnpm-workspace.yaml

Integration branch for gas sponsorship

gas sponsorship feature branch

---

examples/external-match/CHANGELOG.md
examples/external-match/package.json
examples/gas-sponsorship/CHANGELOG.md
examples/gas-sponsorship/package.json
packages/core/CHANGELOG.md
packages/core/package.json
packages/core/src/errors/base.ts
packages/core/src/errors/websocket.ts
packages/core/src/utils.d.ts
packages/core/src/utils/websocket.ts
packages/core/src/utils/websocketWaiter.ts
packages/node/CHANGELOG.md
packages/node/package.json
packages/react/CHANGELOG.md
packages/react/package.json
packages/react/src/errors/base.ts
packages/react/src/errors/context.ts
packages/test/CHANGELOG.md
packages/test/package.json
pnpm-lock.yaml

This PR adds additional checks in the WebSocket implementation, namely ensuring the connection is open before making requests.

core: define and handle ws errors

---

packages/core/package.json
pnpm-lock.yaml

This PR removes an unused dependency.

chore: remove dup ws dep

---

packages/react/src/hooks/useOrderHistoryWebSocket.ts
packages/react/src/hooks/useTaskHistoryWebSocket.ts
packages/react/src/hooks/useWalletWebSocket.ts
packages/react/src/utils/websocket.ts

This PR ensures unsubscribe messages are sent on wallet id change.

react: unsubscribe on wallet id change

---

examples/malleable-external-match/.env.example
examples/malleable-external-match/README.md
examples/malleable-external-match/index.ts
examples/malleable-external-match/package.json
packages/core/src/actions/assembleMalleableQuote.ts
packages/core/src/constants.ts
packages/core/src/exports/actions.ts
packages/core/src/exports/index.ts
packages/core/src/types/fixedPoint.ts
packages/core/src/types/malleableMatch.ts
packages/core/src/types/match.ts
packages/core/src/types/order.ts
packages/core/src/utils.d.ts
pnpm-lock.yaml

This PR adds the `assembleMalleableQuote` action, along with an example.

core: add assemble malleable ext match action

---

examples/external-match/CHANGELOG.md
examples/external-match/package.json
examples/in-kind-gas-sponsorship/CHANGELOG.md
examples/in-kind-gas-sponsorship/package.json
examples/malleable-external-match/CHANGELOG.md
examples/malleable-external-match/package.json
examples/native-eth-gas-sponsorship/CHANGELOG.md
examples/native-eth-gas-sponsorship/package.json
packages/core/src/version.ts
packages/node/CHANGELOG.md
packages/node/package.json
packages/node/src/clients/renegade/index.ts
packages/price-reporter/CHANGELOG.md
packages/price-reporter/package.json
packages/price-reporter/src/client.ts
packages/price-reporter/src/index.ts
packages/token/CHANGELOG.md
packages/token/package.json
packages/token/src/index.ts

This PR includes miscellaneous tweaks that came up while integrating the SDK into the bot server.

node, token, price-reporter: misc adjustments

---

examples/external-match/CHANGELOG.md
examples/external-match/package.json
examples/in-kind-gas-sponsorship/CHANGELOG.md
examples/in-kind-gas-sponsorship/package.json
examples/malleable-external-match/CHANGELOG.md
examples/malleable-external-match/package.json
examples/native-eth-gas-sponsorship/CHANGELOG.md
examples/native-eth-gas-sponsorship/package.json
packages/core/CHANGELOG.md
packages/core/package.json
packages/core/src/constants.ts
packages/core/src/version.ts
packages/node/CHANGELOG.md
packages/node/package.json
packages/price-reporter/CHANGELOG.md
packages/price-reporter/package.json
packages/price-reporter/src/client.ts
packages/price-reporter/src/constants.ts
packages/react/CHANGELOG.md
packages/react/package.json
packages/test/CHANGELOG.md
packages/test/package.json
packages/token/CHANGELOG.md
packages/token/package.json

This PR moves the recently added environments enum to the core packaage.

core: add env enum

---

packages/token-nextjs/CHANGELOG.md
packages/token-nextjs/README.md
packages/token-nextjs/package.json
packages/token-nextjs/src/index.ts
packages/token-nextjs/tsconfig.build.json
packages/token-nextjs/tsconfig.json
pnpm-lock.yaml

This PR adds a package meant for using Token in Next.js environments.
In a follow up PR will make it multi-chain.

token-nextjs: init

---

packages/core/src/utils.d.ts
packages/react/CHANGELOG.md
packages/react/package.json
packages/react/src/exports/index.ts

This PR exports necessary helpers in the react package.

react: export getSDKConfig

---

examples/supported-tokens/.env.example
examples/supported-tokens/README.md
examples/supported-tokens/index.ts
examples/supported-tokens/package.json
pnpm-lock.yaml

This PR adds examples for retrieving both supported tokens and their prices.

examples: add supported tokens examples

---

packages/core/src/exports/actions.ts
packages/react/src/hooks/useIsIndexed.ts

This PR exports needed helpers.

react: ensure ws topic subscription happens after indexing (#224)

---

examples/external-match/base-sepolia/package.json
examples/external-match/basic/package.json
examples/external-match/in-kind-gas-sponsorship/package.json
examples/external-match/malleable/package.json
examples/external-match/native-gas-sponshorship/package.json
examples/external-match/supported-tokens/package.json
examples/external-match/token-prices/README.md
examples/external-match/token-prices/env.ts
examples/external-match/token-prices/index.ts
examples/external-match/token-prices/package.json
examples/external-match/token-prices/tsconfig.json
examples/relayer/cancel-order/package.json
examples/relayer/create-wallet/package.json
examples/relayer/deposit/package.json
examples/relayer/get-order-history/package.json
examples/relayer/get-wallet/package.json
examples/relayer/lookup-wallet/package.json
examples/relayer/pay-fees/package.json
examples/relayer/place-order/package.json
examples/relayer/withdraw/package.json
examples/token/async-initialization/package.json
examples/token/sync-initialization/package.json
pnpm-lock.yaml

examples: external match: add token prices
